services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant 
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - qdb
    restart: always

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference
    container_name: tei_q 
    environment:
      MODEL_ID: Qwen/Qwen3-Embedding-0.6B
    ports:
      - 8083:80 # tcp
    volumes:
      - ~/.cache/huggingface/:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
    networks:
      - qdb
    restart: always

  eserv:
    build:
      context: ./easyapp
    container_name: eserv
    hostname: eserv
    ports:
      - "8041:8041"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
    networks:
      - qdb
  vectdba:
    image: pgvector/pgvector:0.8.0-pg17-trixie  # Prebuilt Postgres image with pgvector
    container_name: pgvectora
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: embedding_db
    volumes:
      - ~/docker/rag/pgdata/:/var/lib/postgresql/data
    networks:
      - qdb    
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - vectdba
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    networks:
      - qdb       

volumes:
  qdrant_data:


networks:
  qdb: